{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "mediawiki.fullname" . }}-ingress-service
  annotations:
{{ toYaml .Values.ingress.annotations | indent 3 }}
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
                serviceName: {{ template "mediawiki.fullname" . }}-service
                servicePort: 80
{{- end -}}