apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediawiki.fullname" . }}-service
spec:
  selector:
    component: {{ template "mediawiki.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: 80
  {{- if .Values.service.httpsPort }}
  - name: "https"
    port: {{ .Values.service.httpsPort }}
    targetPort: 443
  {{- end }}