{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "mediawiki.fullname" . }}
spec:
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  scaleTargetRef:
    kind: Deployment
    name: {{ template "mediawiki.fullname" . }}
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.averageUtilization }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
{{- end -}}