apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mediawiki.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "mediawiki.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        component: {{ template "mediawiki.fullname" . }}
    spec:
      containers:
        - name: php
          image: {{ template "mediawiki.image" . }}
          command:
            - sh
            - -c
          args:
            - php /var/www/html/maintenance/install.php --dbname=$wgDBname --dbserver=$wgDBserver --installdbuser=root --installdbpass=$wgDBpassword --dbuser=$wgDBuser --dbpass=$wgUserDBpassword --server='http://192.168.57.211' --scriptpath='' --lang=en --pass=aaaaa 'Wiki Name' 'Admin' && exec /usr/sbin/php-fpm --nodaemonize
          volumeMounts:
            - mountPath: /run/php-fpm/
              name: socket
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: wgDBname
              value: {{ template "mediawiki.fullname" . }}
            - name: wgDBpassword
              valueFrom:
                secretKeyRef:
                  name: {{ template "mediawiki.fullname" . }}
                  key: MYSQL-ROOT-PASSWORD
            - name: wgDBuser
              value: {{ .Values.dbuser }}
            - name: wgUserDBpassword
              valueFrom:
                secretKeyRef:
                  name: {{ template "mediawiki.fullname" . }}
                  key: MYSQL-WIKIUSER-PASSWORD
            - name: wgDBserver
              value: {{ template "mediawiki.fullname" . }}-mysql-service
        - name: apache
          image: {{ template "mediawiki.image" . }}
          command:
            - /run-httpd.sh
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /run/php-fpm/
              name: socket
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
      - name: socket
        emptyDir: {}
