apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "mediawiki.fullname" . }}
spec:
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: {{ template "mediawiki.fullname" . }}
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 5
  minReplicas: 2