apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediawiki.fullname" . }}-service
spec:
  selector:
    component: {{ template "mediawiki.fullname" . }}
  type: ClusterIP
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443