apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediawiki.fullname" . }}-mysql-service
spec:
  selector:
    component: {{ template "mediawiki.fullname" . }}-mysql
  type: {{ .Values.service.type }}
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306

