apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mediawiki.fullname" . }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ template "mediawiki.fullname" . }}-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: {{ template "mediawiki.fullname" . }}-mysql
    spec:
      containers:
      - env:
        # - name: MYSQL_DATABASE
        #   value: media_wiki
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mediawiki.fullname" . }}
              key: MYSQL-ROOT-PASSWORD
        image: mysql:5.7.22
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: mysql
        ports:
        - containerPort: 3306
        tty: true
        volumeMounts:
        - mountPath: /var/lib/mysql/
          name: {{ template "mediawiki.fullname" . }}-dbdata
      restartPolicy: Always
      volumes:
      - name: {{ template "mediawiki.fullname" . }}-dbdata
        persistentVolumeClaim:
          claimName: {{ template "mediawiki.fullname" . }}-dbdata
