apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mediawiki.fullname" . }}-php
spec:
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
