apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mediawiki.fullname" . }}
  labels:
    app: {{ template "mediawiki.name" . }}
type: Opaque
data:
  MYSQL-ROOT-PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  MYSQL-WIKIUSER-PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}